# Generated by Django 5.2.11 on 2026-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('venue', 'Venue'), ('caterer', 'Caterer'), ('decorator', 'Decorator'), ('musician', 'Musician')], max_length=20)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
